### PR TITLE
update my details saikrishna_11

### PR DESCRIPTION
**Pull request by knsskrishna**
Hi Sekhar,

          I have completed my changes in my file like
Name
Batch
Roll No
City
        and also update in Daily file.

      Please check it review and Approval my file

Thank you,
Saikrishna,
Roll No-11,
Batch-23B.

### CODE REVIEW

**Comment by knsskrishna** [comment]
@psomasekhar  please check it my files review and Approval.

**Review by shaikansari786 — APPROVED** [review]
approved

**Review by psomasekhar — APPROVED** [review]
Ok

**Review by psomasekhar — APPROVED** [review]

**Review by shaikansari786 — APPROVED** [review]
approved

**Pull request merged**
